alias b="npm run build:server:dev; and notify -t 'build:SERVER:dev' -m 'OKAY'"
alias c="npm run build:client:dev; and notify -t 'build:CLIENT:dev' -m 'OKAY'"
alias s="npm run start:dev"
alias lintc="npm run lint:client"
alias lints="npm run lint:server"
alias bs="b; and s"
